
from pathlib import Path


# data locations...
HOME = Path.home()
LOCAL_DATABASE = HOME / 'CAELUS-DATA'
REMOTE_FILE_PATTERN = 'https://zenodo.org/record/7897639/files/{0}?download=1'

# max. solar zenith angle, degrees
MAX_SZA = 85.

# moving average time windows
DT = '30T'
DT_F = '10T'

# thresholds (Table 3)
CLOUDEN_MIN_KCS = 1.06
CLOUDLESS_MIN_KM = 0.6
CLOUDLESS_MIN_KCS = 0.85
CLOUDLESS_MAX_KCS = 1.15
THINCLOUDS_MIN_KM = 0.5
THICKCLOUDS_MAX_KM = 0.4
OVERCAST_MAX_KM = 0.3
CLOUDEN_MIN_KV = 0.20
CLOUDEN_MIN_KVF = 0.20
CLOUDLESS_MAX_KV = 0.03
THINCLOUDS_MIN_KV = 0.03
THINCLOUDS_MAX_KV = 0.08
THICKCLOUDS_MIN_KV = 0.04
THICKCLOUDS_MAX_KV = 0.16
OVERCAST_MAX_KV = 0.10

# options for cleaning filters (section 3.2)
CLEAN_SPURIOUS_SKY_PATCHES = True
CLEAN_SCATTER_CLOUDS_FLANKED_BY_THIN_CLOUDS = True
CLEAN_CLOUDLESS_TO_THIN_CLOUDS_TRANSITIONS = True
CLEAN_THIN_CLOUDS_TO_SCATTER_CLOUDS_TRANSITIONS = True
